### ISSUE TITLE
Check if ROS is installed

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#1]
I think that it is better to check if ROS is installed in the machine before installing it

If you do "rosversion -d" it should say "kinetic" if it is installed in Ubuntu 16.04

**Comment by Nbot07** [comment]
Let me know or close the issue if this is fine. https://github.com/rafaelxero/jrlutil/commit/03c3a07038dc09bbe0595b2e450c920538e889a3

**Comment by rafaelxero** [comment]
Included also the addition to .bashrc inside of the if check
