### ISSUE TITLE
Make jrlutil ROS-free

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#17]
Related to the issue #16, we checked that ROS is actually not needed for the way that we are using the JRL software, so I propose to make the appropriate changes to make jrlutil ROS free:

- We don't need to install ROS anymore
- We don't need to create the catkin_ws directory
- We don't need to clone the repositories for hrp2_drc, hrp4 or mc_rtc_ros anymore

Instead:
- We just need to install hrp5_p_description and mc_rtc_ros_data directly at the jrl directory
  (they were previously under catkin_ws/src), installing them in the usual way
  (create build directory, do ccmake to configure them like the other packages, make, make install)

**Comment by rafaelxero** [comment]
@mehdi-benallegue, can you check if the branch ROS-free work in a clean environment? 
I modified the scripts to remove the ROS dependency

**Comment by mehdi-benallegue** [comment]
Tested, PR https://github.com/rafaelxero/jrlutil/pull/18 sent
