### ISSUE TITLE
make install or sudo make install

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#2]
If the user is installing in home directory the compilation/installation should be with "make -j8" / "make -j8 install" but if it is being installed in /usr then the compilation should be with "make -j8" / "sudo make -j8 install"

**Comment by Nbot07** [comment]
Please review https://github.com/rafaelxero/jrlutil/commit/ff50b6a52fe32798e41811e4877a4b03b6cb60e4
