### ISSUE TITLE
Turn on option and build HMC in C++11 mode

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#3]
In build_hmc I think that it is necessary to turn ON the option:
BUILD_MULTI_CONTACT_MOTION_SOLVER

Also, to add the flag to compile in C++11 or it will fail

**Comment by Nbot07** [comment]
How did you add the flag to compile in C++11?

**Comment by rafaelxero** [comment]
Add -std=c++11 to CMAKE_CXX_FLAGS

**Comment by Nbot07** [comment]
For clarity, when I do, `ccmake .`, the CMAKE_CXX_FLAGS option does not appear. 
This is also the case if I do `cmake -D CMAKE_CXX_FLAGS="-std=c++11" .` then check with `ccmake .`. 
So, I'm not sure if -std=c++11 is being added to the CMAKE_CXX_FLAGS option. 

Let me know your thoughts. Also, I updated the option here: https://github.com/rafaelxero/jrlutil/commit/165e7311429b551e7e347ad6c9d87476e2a61a06

**Comment by Nbot07** [comment]
Thanks for letting me know about toggling the advanced options for cmake. Here is the update for the flags: https://github.com/rafaelxero/jrlutil/commit/566667d3c3f6ab46c9a1f6a0f2c34e37b9d5f761
