### ISSUE TITLE
/$SRC_DIR

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#4]
as $HOME already contains /home/<...>, it is not necessary to do /$SRC_DIR
It writes in .bashrc the following:
source //home/...

**Comment by Nbot07** [comment]
It is inconsequential. However, please let me know if you would still like me to update the repo to prevent extra forward slashes in directory paths. https://stackoverflow.com/posts/20690872/edit

**Comment by rafaelxero** [comment]
It is better... for it to be "clean"

**Comment by Nbot07** [comment]
Ok, I updated the repo here: https://github.com/rafaelxero/jrlutil/commit/5643b97ddfe9d2e86887b2493ee454a1ee54e07c
