### ISSUE TITLE
catkin_init_workspace: command not found

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#5]
Right after installing ROS the installation fails due to the following messages:

./install.sh: line 65: catkin_init_workspace: command not found
./install.sh: line 67: catkin_make: command not found

It seems that it does not recognize immediately the command catkin_init_workspace, but after a while... maybe it is a good idea to use

updatedb

just before catkin_init_workspace

**Comment by Nbot07** [comment]
https://github.com/rafaelxero/jrlutil/commit/aea511a5e1122f8ece3765a4a0ab4a7f93b6cf7d
