### ISSUE TITLE
Errors when installing mc_rtc

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#7]
Right after installing Tasks got the following errors:

Base path: //home/rcisneros/src/jrl/catkin_ws
Source space: //home/rcisneros/src/jrl/catkin_ws/src
The specified base path "//home/rcisneros/src/jrl/catkin_ws" contains a CMakeLists.txt but "catkin_make" must be invoked in the root of workspace
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Performing Test R-pedantic
-- Performing Test R-pedantic - Success
-- Performing Test R-Wno-long-long
-- Performing Test R-Wno-long-long - Success
-- Performing Test R-Wall
-- Performing Test R-Wall - Success
-- Performing Test R-Wextra
-- Performing Test R-Wextra - Success
-- Performing Test R-Wcast-align
-- Performing Test R-Wcast-align - Success
-- Performing Test R-Wcast-qual
-- Performing Test R-Wcast-qual - Success
-- Performing Test R-Wformat
-- Performing Test R-Wformat - Success
-- Performing Test R-Wwrite-strings
-- Performing Test R-Wwrite-strings - Success
-- Performing Test R-Wconversion
-- Performing Test R-Wconversion - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   timer
--   system
--   chrono
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
-- Found LTDL: /usr/lib/x86_64-linux-gnu/libltdl.so  
CMake Error at CMakeModules/Findmc_rtc_3rd_party_geos.cmake:37 (message):
  Found GEOS install prefix (/usr) but no geos library
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_rtc/build/CMakeFiles/CMakeOutput.log".
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   timer
--   system
--   chrono
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
CMake Error at CMakeModules/Findmc_rtc_3rd_party_geos.cmake:37 (message):
  Found GEOS install prefix (/usr) but no geos library
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_rtc/build/CMakeFiles/CMakeOutput.log".
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   timer
--   system
--   chrono
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
CMake Error at CMakeModules/Findmc_rtc_3rd_party_geos.cmake:37 (message):
  Found GEOS install prefix (/usr) but no geos library
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_rtc/build/CMakeFiles/CMakeOutput.log".
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   timer
--   system
--   chrono
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
CMake Error at CMakeModules/Findmc_rtc_3rd_party_geos.cmake:37 (message):
  Found GEOS install prefix (/usr) but no geos library
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_rtc/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'eigen3 >= 3.0.0'
--   Found eigen3 , version 3.2.92
Warning: failed to compute the version number, 'git describe' failed:
	fatal: No names found, cannot describe anything.

-- Performing Test R-pedantic
-- Performing Test R-pedantic - Success
-- Performing Test R-Wno-long-long
-- Performing Test R-Wno-long-long - Success
-- Performing Test R-Wall
-- Performing Test R-Wall - Success
-- Performing Test R-Wextra
-- Performing Test R-Wextra - Success
-- Performing Test R-Wcast-align
-- Performing Test R-Wcast-align - Success
-- Performing Test R-Wcast-qual
-- Performing Test R-Wcast-qual - Success
-- Performing Test R-Wformat
-- Performing Test R-Wformat - Success
-- Performing Test R-Wwrite-strings
-- Performing Test R-Wwrite-strings - Success
-- Performing Test R-Wconversion
-- Performing Test R-Wconversion - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- mc_rtc is required.
-- Checking for module 'mc_rtc'
--   No package 'mc_rtc' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  cmake/pkg-config.cmake:282 (PKG_CHECK_MODULES)
  cmake/pkg-config.cmake:447 (ADD_DEPENDENCY)
  CMakeLists.txt:23 (add_required_dependency)

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_hrp5_p/build/CMakeFiles/CMakeOutput.log".
-- Checking for module 'eigen3 >= 3.0.0'
--   Found eigen3 , version 3.2.92
Warning: failed to compute the version number, 'git describe' failed:
	fatal: No names found, cannot describe anything.

-- mc_rtc is required.
-- Checking for module 'mc_rtc'
--   No package 'mc_rtc' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  cmake/pkg-config.cmake:282 (PKG_CHECK_MODULES)
  cmake/pkg-config.cmake:447 (ADD_DEPENDENCY)
  CMakeLists.txt:23 (add_required_dependency)

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_hrp5_p/build/CMakeFiles/CMakeOutput.log".
-- Checking for module 'eigen3 >= 3.0.0'
--   Found eigen3 , version 3.2.92
Warning: failed to compute the version number, 'git describe' failed:
	fatal: No names found, cannot describe anything.

-- mc_rtc is required.
-- Checking for module 'mc_rtc'
--   No package 'mc_rtc' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  cmake/pkg-config.cmake:282 (PKG_CHECK_MODULES)
  cmake/pkg-config.cmake:447 (ADD_DEPENDENCY)
  CMakeLists.txt:23 (add_required_dependency)

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_hrp5_p/build/CMakeFiles/CMakeOutput.log".
-- Checking for module 'eigen3 >= 3.0.0'
--   Found eigen3 , version 3.2.92
Warning: failed to compute the version number, 'git describe' failed:
	fatal: No names found, cannot describe anything.

-- mc_rtc is required.
-- Checking for module 'mc_rtc'
--   No package 'mc_rtc' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  cmake/pkg-config.cmake:282 (PKG_CHECK_MODULES)
  cmake/pkg-config.cmake:447 (ADD_DEPENDENCY)
  CMakeLists.txt:23 (add_required_dependency)

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_hrp5_p/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
CMake Warning (dev) at cmake/version.cmake:104 (MESSAGE):
  Warning: failed to compute the version number, 'git describe' failed:

  	fatal: No names found, cannot describe anything.

Call Stack (most recent call first):
  cmake/base.cmake:182 (VERSION_COMPUTE)
  CMakeLists.txt:22 (setup_project)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test R-pedantic
-- Performing Test R-pedantic - Success
-- Performing Test R-Wno-long-long
-- Performing Test R-Wno-long-long - Success
-- Performing Test R-Wall
-- Performing Test R-Wall - Success
-- Performing Test R-Wextra
-- Performing Test R-Wextra - Success
-- Performing Test R-Wcast-align
-- Performing Test R-Wcast-align - Success
-- Performing Test R-Wcast-qual
-- Performing Test R-Wcast-qual - Success
-- Performing Test R-Wformat
-- Performing Test R-Wformat - Success
-- Performing Test R-Wwrite-strings
-- Performing Test R-Wwrite-strings - Success
-- Performing Test R-Wconversion
-- Performing Test R-Wconversion - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "Findmc_rtc.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "mc_rtc", but
  CMake did not find one.

  Could not find a package configuration file provided by "mc_rtc" with any
  of the following names:

    mc_rtcConfig.cmake
    mc_rtc-config.cmake

  Add the installation prefix of "mc_rtc" to CMAKE_PREFIX_PATH or set
  "mc_rtc_DIR" to a directory containing one of the above files.  If "mc_rtc"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_openrtm/build/CMakeFiles/CMakeOutput.log".
CMake Warning (dev) at cmake/version.cmake:104 (MESSAGE):
  Warning: failed to compute the version number, 'git describe' failed:

  	fatal: No names found, cannot describe anything.

Call Stack (most recent call first):
  cmake/base.cmake:182 (VERSION_COMPUTE)
  CMakeLists.txt:22 (setup_project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "Findmc_rtc.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "mc_rtc", but
  CMake did not find one.

  Could not find a package configuration file provided by "mc_rtc" with any
  of the following names:

    mc_rtcConfig.cmake
    mc_rtc-config.cmake

  Add the installation prefix of "mc_rtc" to CMAKE_PREFIX_PATH or set
  "mc_rtc_DIR" to a directory containing one of the above files.  If "mc_rtc"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_openrtm/build/CMakeFiles/CMakeOutput.log".
CMake Warning (dev) at cmake/version.cmake:104 (MESSAGE):
  Warning: failed to compute the version number, 'git describe' failed:

  	fatal: No names found, cannot describe anything.

Call Stack (most recent call first):
  cmake/base.cmake:182 (VERSION_COMPUTE)
  CMakeLists.txt:22 (setup_project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "Findmc_rtc.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "mc_rtc", but
  CMake did not find one.

  Could not find a package configuration file provided by "mc_rtc" with any
  of the following names:

    mc_rtcConfig.cmake
    mc_rtc-config.cmake

  Add the installation prefix of "mc_rtc" to CMAKE_PREFIX_PATH or set
  "mc_rtc_DIR" to a directory containing one of the above files.  If "mc_rtc"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_openrtm/build/CMakeFiles/CMakeOutput.log".
CMake Warning (dev) at cmake/version.cmake:104 (MESSAGE):
  Warning: failed to compute the version number, 'git describe' failed:

  	fatal: No names found, cannot describe anything.

Call Stack (most recent call first):
  cmake/base.cmake:182 (VERSION_COMPUTE)
  CMakeLists.txt:22 (setup_project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:29 (find_package):
  By not providing "Findmc_rtc.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "mc_rtc", but
  CMake did not find one.

  Could not find a package configuration file provided by "mc_rtc" with any
  of the following names:

    mc_rtcConfig.cmake
    mc_rtc-config.cmake

  Add the installation prefix of "mc_rtc" to CMAKE_PREFIX_PATH or set
  "mc_rtc_DIR" to a directory containing one of the above files.  If "mc_rtc"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "//home/rcisneros/src/jrl/mc_openrtm/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
Cloning into 'mc_rtc_ros'...
remote: Enumerating objects: 1811, done.
remote: Counting objects: 100% (1811/1811), done.
remote: Compressing objects: 100% (508/508), done.
remote: Total 1811 (delta 1299), reused 1758 (delta 1253)
Receiving objects: 100% (1811/1811), 672.22 KiB | 311.00 KiB/s, done.
Resolving deltas: 100% (1299/1299), done.
Checking connectivity... done.
Submodule '.jrl-ci' (https://github.com/jrl-umi3218/jrl-travis) registered for path '.jrl-ci'
Cloning into '.jrl-ci'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 791 (delta 15), reused 24 (delta 12), pack-reused 757
Receiving objects: 100% (791/791), 158.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (490/490), done.
Checking connectivity... done.
Submodule path '.jrl-ci': checked out 'e3853d4514351a2f3e5e67f6ecd963fce5ae5ef5'
Base path: //home/rcisneros/src/jrl/catkin_ws
Source space: //home/rcisneros/src/jrl/catkin_ws/src
The specified base path "//home/rcisneros/src/jrl/catkin_ws" contains a CMakeLists.txt but "catkin_make" must be invoked in the root of workspace
./install.sh: line 238: ./build_hmc.sh: No such file or directory

**Comment by Nbot07** [comment]
This is likely a consequence of https://github.com/rafaelxero/jrlutil/issues/5, but we'll see.

**Comment by Nbot07** [comment]
Let me know if this is still an issue after pulling the solution to https://github.com/rafaelxero/jrlutil/issues/5.

**Comment by rafaelxero** [comment]
Still getting:

CMake Error at mc_rtc_ros/mc_convex_visualization/CMakeLists.txt:17 (find_package):
  By not providing "Findmc_rtc.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "mc_rtc", but
  CMake did not find one.

  Could not find a package configuration file provided by "mc_rtc" with any
  of the following names:

    mc_rtcConfig.cmake
    mc_rtc-config.cmake

  Add the installation prefix of "mc_rtc" to CMAKE_PREFIX_PATH or set
  "mc_rtc_DIR" to a directory containing one of the above files.  If "mc_rtc"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/rcisneros/src/jrl/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/rcisneros/src/jrl/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
./install.sh: line 238: ./build_hmc.sh: No such file or directory

**Comment by rafaelxero** [comment]
Also, got

-- Configuring incomplete, errors occurred!
See also "/home/rcisneros/src/jrl/mc_rtc/build/CMakeFiles/CMakeOutput.log".
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   timer
--   system
--   chrono
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
CMake Error at CMakeModules/Findmc_rtc_3rd_party_geos.cmake:37 (message):
  Found GEOS install prefix (/usr) but no geos library
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)

**Comment by rafaelxero** [comment]
I think that you missed to do in install.sh:
sudo apt install libgeos++-dev

**Comment by Nbot07** [comment]
https://github.com/rafaelxero/jrlutil/commit/f0ee662e4df59f37122516e12686c5c763e18ba5

**Comment by rafaelxero** [comment]
The script could run "in parts" yesterday, but when trying to do it in one run I saw the following message:

-- Checking for module 'mc_rtc'
--   Found mc_rtc, version 0.1.0-1639-g3685e-dirty
-- Pkg-config module mc_rtc v0.1.0-1639-g3685e-dirty has been detected with success.
-- hrp5_p_description is required.
-- Checking for module 'hrp5_p_description'
--   No package 'hrp5_p_description' found

**Comment by rafaelxero** [comment]
Can you print messages in the screen indicating which command or set of commands are being executed? Like "Cloning mc_rtc", "Configuring mc_rtc", "Building mc_rtc", "Installing mc_rtc" and so on for all the steps in the script... Right now it is difficult to match the outcome with the script

**Comment by Nbot07** [comment]
Let me know if this helps. https://github.com/rafaelxero/jrlutil/commit/b623bdb0c92e1980b79d24c22f4fa8153f3a5ec0
