### ISSUE TITLE
Issue with mc_rtc_ros

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#8]
In the current installation procedure, mc_rtc_ros is cloned after installing everything else...

Let's assume that the installation fails at some point and it is necessary to re-run it again
In such a case mc_rtc_ros already exists when doing catkin_make for the "first time", leading to the interdependency error with mc_rtc

Maybe it is better to check for its existence during the first catkin_make, and maybe delete it if it exists

**Comment by Nbot07** [comment]
https://github.com/rafaelxero/jrlutil/commit/fd6a9bed47e2933f5cff2c4125c5861b8d611a72
