### ISSUE TITLE
nanomsg installation

### ISSUE THREAD

**Issue by rafaelxero** [rafaelxero/jrlutil#9]
It is probably better to install nanomsg in $INSTALL_DIR also
(using sudo or not depending on where it is)

**Comment by Nbot07** [comment]
https://github.com/rafaelxero/jrlutil/commit/24c914c46942cf54be19f36d485f835be7dc6e68

**Comment by rafaelxero** [comment]
This modification puts the soruce code of nanomsg in openrtp and installs it in usr/local

**Comment by Nbot07** [comment]
oh ok. Let me know if this is good. https://github.com/rafaelxero/jrlutil/commit/23cb295c1f73ec74391c43bd82a3e37ac4094a4c
